version: '3'
services:

  server:
    container_name: eduzz-fidic-agreement
    build:
      context: ../
      dockerfile: ./back/docker/dev/Dockerfile
    volumes:
      - ..:/app
    ports:
      - 5000:5000
      - 9229:9229
    env_file: ./.env