library 'EcsDeploy'

def buildNumber = env.BUILD_NUMBER as int
if (buildNumber > 1) milestone(buildNumber - 1)
milestone(buildNumber)

node {
  def dockerImage
  
  stage ('Clone Repository') {
    checkout scm
  }

  stage ('Build container') {
    dockerImage = docker.build('eduzz-fidic-agreement', "-f docker/prod/Dockerfile --build-arg VERSION=\"${env.BRANCH_NAME}-${env.BUILD_NUMBER}\" . ")
  }

  stage('Publish to ECR') {
    if (env.BRANCH_NAME ==~ /(master)/) {
      docker.withRegistry("https://${env.ECR_URL}", env.ECR_CRED) {
        dockerImage.push("${env.BRANCH_NAME}-${env.BUILD_NUMBER}")
      }
    }

    if (env.BRANCH_NAME ==~ /(hotfix.*|release.*|develop)/) {
      docker.withRegistry("https://${env.ECR_URL}", env.ECR_CRED) {
        dockerImage.push("${env.BRANCH_NAME}")
      }
    }
  }

  stage('Deploy') {
   if (env.BRANCH_NAME ==~ /(master)/) {
      ecsDeploy('prod', "${env.BRANCH_NAME}-${env.BUILD_NUMBER}")
    }

    if (env.BRANCH_NAME ==~ /(release.*|hotfix.*|develop)/) {
      ecsDeploy('homolog', "${env.BRANCH_NAME}")
    }
  }

  stage('Clean') {
    cleanWs()
  }

}